.TH dfm 1 "December 2016" "0.1.0" "dfm man page"
.SH NAME
dfm \- A configuration file manager
.SH SYNOPSIS
dfm [vp] [-i|-u|-c] [-d directory] [-a|[MODULES]]
.SH DESCRIPTION
Used for installing, uninstalling, and updating configuration files for a user.
It operates on a directory, which defaults to the current directory, and opens a
file called config.dfm.
Must be passed --insall, --uninstall, or --check as an operation, and must
either be passed the --all flag or a list of modules.
.IP "-d, --directory"
Specify the directory to work in, defaults to the current directory
.IP "-i, --install"
Install the given modules
.IP "-u, --uninstall"
Uninstall the given modules
.IP "-c, --check"
Check the installable files for if they need to be updated.
.IP "-a, --all"
Perform the operation on all modules
.IP "-p, --prompt"
Ask for confirmation when operating on modules, manipulating files, etc.
Ask for the command to install the specified dependencies for a module.
.IP "-v, --verbose"
Print extra information
.SH AUTHOR
Jason Waataja <jasonswaataja@gmail.com>
